import { StyleSheet, Platform } from 'react-native';
import { CONTENT_MAX_WIDTH, FONTS, THEME, safeArea } from './lib/layout';

export function createStyles(screenWidth) {
  const imageSize = screenWidth * 0.88;

  return StyleSheet.create({
    container: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
    },
    scrollView: {
      flex: 1,
      width: '100%',
    },
    scrollOuter: {
      alignItems: 'center',
      width: '100%',
      paddingTop: safeArea.paddingTop,
      paddingBottom: safeArea.paddingBottom,
      paddingLeft: safeArea.paddingLeft,
      paddingRight: safeArea.paddingRight,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: safeArea.paddingTop,
    },
    loadingText: {
      color: '#fff',
      fontSize: 18,
      marginTop: 20,
      fontWeight: '600',
    },
    dayText: {
      fontSize: 15,
      fontWeight: '300',
      color: '#fff',
      textAlign: 'center',
      marginBottom: 16,
      paddingHorizontal: 12,
      lineHeight: 26,
      textShadowColor: '#00000066',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 2,
      fontFamily: FONTS.display,
      letterSpacing: 0.3,
      fontStyle: 'italic',
      maxWidth: imageSize,
    },
    enrichErrorText: {
      color: '#fecaca',
      fontSize: 13,
      textAlign: 'center',
      marginBottom: 8,
      maxWidth: imageSize,
    },
    daysLeftText: {
      fontSize: 26,
      fontWeight: '800',
      color: '#fff',
      marginBottom: 6,
      textShadowColor: '#00000088',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
      textAlign: 'center',
      maxWidth: imageSize,
    },
    birthdayHeaderText: {
      fontSize: 30,
      letterSpacing: 0.5,
    },
    calendarDateText: {
      color: '#f1f5f9',
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 10,
      textAlign: 'center',
      opacity: 0.95,
    },
    backToTodayBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(255,255,255,0.2)',
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.35)',
    },
    backToTodayText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 14,
    },
    cacheBanner: {
      backgroundColor: 'rgba(255,255,255,0.15)',
      borderRadius: 10,
      padding: 10,
      marginBottom: 10,
      width: '100%',
      maxWidth: imageSize,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    cacheBannerText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '600',
      textAlign: 'center',
    },
    previewBanner: {
      width: '100%',
      maxWidth: imageSize,
      backgroundColor: 'rgba(251, 191, 36, 0.95)',
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      gap: 6,
    },
    previewBannerText: {
      color: '#78350f',
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
    },
    previewBannerLink: {
      color: THEME.primary,
      fontWeight: '800',
      fontSize: 13,
      textAlign: 'center',
    },
    imageContainer: {
      width: imageSize,
      height: imageSize,
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: '#fff',
      shadowColor: '#000',
      shadowOpacity: 0.28,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 12,
      marginBottom: 14,
    },
    birthdayImageContainer: {
      borderWidth: 3,
      borderColor: '#fbbf24',
      shadowColor: THEME.secondary,
      shadowOpacity: 0.5,
      shadowRadius: 20,
    },
    enrichingOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 2,
      backgroundColor: 'rgba(255,255,255,0.65)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    image: {
      width: '100%',
      height: '100%',
    },
    imageWrap: {
      width: '100%',
      height: '100%',
      position: 'relative',
    },
    imageGiftBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: 'rgba(196, 92, 106, 0.93)',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
    },
    imageGiftBadgeText: {
      color: '#fff',
      fontWeight: '800',
      fontSize: 12,
    },
    carousel: {
      width: '100%',
      height: '100%',
    },
    carouselItem: {
      width: imageSize,
      height: imageSize,
    },
    carouselImage: {
      width: '100%',
      height: '100%',
      borderRadius: 22,
    },
    paginationContainer: {
      position: 'absolute',
      bottom: 14,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    paginationDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: 'rgba(255, 255, 255, 0.5)',
      marginHorizontal: 4,
    },
    paginationDotActive: {
      backgroundColor: '#fff',
      width: 12,
      height: 12,
      borderRadius: 6,
    },
    button: {
      backgroundColor: 'rgba(15, 44, 46, 0.85)',
      borderRadius: 44,
      marginBottom: 20,
      shadowColor: THEME.primary,
      shadowOpacity: 0.6,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
      elevation: 8,
      minHeight: 48,
      minWidth: 48,
    },
    giftButtonSmall: {
      backgroundColor: THEME.secondary,
      borderRadius: 32,
      width: 64,
      height: 64,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: THEME.secondary,
      shadowOpacity: 0.8,
      shadowRadius: 15,
      shadowOffset: { width: 0, height: 8 },
      elevation: 12,
      marginTop: 12,
      alignSelf: 'center',
      borderWidth: 2,
      borderColor: '#fff3',
    },
    giftButtonPulse: {
      shadowOpacity: 1,
      shadowRadius: 22,
    },
    pressable: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      paddingHorizontal: 20,
      minHeight: 48,
      minWidth: 48,
    },
    audioControls: {
      width: '100%',
      maxWidth: imageSize,
      marginTop: -8,
      marginBottom: 20,
      paddingHorizontal: 4,
    },
    audioTimeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    audioTime: {
      color: '#e2e8f0',
      fontSize: 12,
      fontWeight: '600',
      fontVariant: ['tabular-nums'],
    },
    giftPressable: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    galleryTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: '#fff',
      marginBottom: 10,
      alignSelf: 'flex-start',
      maxWidth: imageSize,
    },
    scroll: {
      maxHeight: 120,
      width: '100%',
      maxWidth: imageSize,
    },
    scrollContent: {
      paddingVertical: 8,
      paddingHorizontal: 8,
    },
    thumbnailContainer: {
      marginHorizontal: 6,
      position: 'relative',
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    thumbnailActive: {
      borderColor: '#fff',
      transform: [{ scale: 1.05 }],
    },
    thumbnailLocked: {
      opacity: 0.35,
    },
    thumbnailGift: {
      borderColor: '#fbbf24',
    },
    thumbnail: {
      width: 92,
      height: 92,
      borderRadius: 14,
    },
    dayBadge: {
      position: 'absolute',
      top: 6,
      left: 6,
      backgroundColor: 'rgba(0,0,0,0.55)',
      borderRadius: 10,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    dayBadgeText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '800',
    },
    giftThumbBadge: {
      position: 'absolute',
      top: 6,
      right: 6,
      backgroundColor: THEME.secondary,
      borderRadius: 12,
      padding: 4,
      minWidth: 24,
      minHeight: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    giftThumbBadgeLocked: {
      backgroundColor: '#94a3b8',
    },
    giftOpenedBadge: {
      position: 'absolute',
      bottom: 6,
      left: 6,
      backgroundColor: 'rgba(255,255,255,0.92)',
      borderRadius: 12,
      padding: 2,
    },
    viewedBadge: {
      position: 'absolute',
      bottom: 6,
      right: 6,
      backgroundColor: 'rgba(255,255,255,0.9)',
      borderRadius: 12,
      padding: 1,
    },
    lockOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255,255,255,0.55)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    preStartWrap: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      paddingTop: safeArea.paddingTop,
      paddingBottom: safeArea.paddingBottom,
      paddingLeft: safeArea.paddingLeft,
      paddingRight: safeArea.paddingRight,
    },
    webInner: {
      width: '100%',
      maxWidth: CONTENT_MAX_WIDTH,
      alignItems: 'center',
    },
  });
}
