import { StyleSheet, Platform } from 'react-native';
import { THEME } from '../lib/layout';

const ADMIN_MAX_WIDTH = 1100;

export const createStyles = (isNarrow, isWide) =>
  StyleSheet.create({
  container: {
    flex: 1,
    ...(Platform.OS === 'web' ? { minHeight: '100dvh' } : { minHeight: '100%' }),
  },
  pageScroll: { flex: 1, width: '100%' },
  pageScrollContent: { flexGrow: 1, paddingBottom: 48 },
  pageInner: {
    width: '100%',
    maxWidth: ADMIN_MAX_WIDTH,
    alignSelf: 'center',
    paddingHorizontal: isNarrow ? 16 : 24,
  },
  blocked: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  blockedText: { color: '#fff', fontSize: 16, textAlign: 'center' },
  loginCard: {
    margin: 'auto',
    width: '100%',
    maxWidth: 420,
    padding: 32,
    alignSelf: 'center',
    paddingTop: 'max(48px, env(safe-area-inset-top, 0px))',
  },
  header: {
    paddingTop: 'max(20px, env(safe-area-inset-top, 0px))',
    paddingBottom: 16,
    flexDirection: isNarrow ? 'column' : 'row',
    justifyContent: 'space-between',
    alignItems: isNarrow ? 'stretch' : 'flex-start',
    gap: 12,
  },
  headerTitleWrap: { flex: isNarrow ? undefined : 1 },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  settingsGrid: {
    flexDirection: isWide ? 'row' : 'column',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
    width: '100%',
  },
  settingsCard: {
    flex: isWide ? 1 : undefined,
    minWidth: isWide ? 280 : undefined,
    width: isWide ? undefined : '100%',
    padding: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  settingsTitle: { color: '#fff', fontSize: 16, fontWeight: '700', marginBottom: 4 },
  settingsHint: { color: '#cbd5e1', fontSize: 13, marginBottom: 8, lineHeight: 18 },
  settingsList: { color: '#94a3b8', fontSize: 12, lineHeight: 17 },
  settingsRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  hourInput: {
    width: 64,
    backgroundColor: '#1e293b',
    color: '#fff',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    fontWeight: '700',
    borderWidth: 1,
    borderColor: '#334155',
    textAlign: 'center',
  },
  hourSuffix: { color: '#e2e8f0', fontSize: 14, fontWeight: '600' },
  primaryBtnSmall: {
    backgroundColor: THEME.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    minHeight: 44,
    justifyContent: 'center',
  },
  title: { color: '#fff', fontSize: 28, fontWeight: '800' },
  subtitle: { color: '#cbd5e1', fontSize: 13, marginTop: 4 },
  layout: {
    flexDirection: isNarrow ? 'column' : 'row',
    width: '100%',
    gap: isNarrow ? 12 : 16,
    alignItems: isNarrow ? 'stretch' : 'flex-start',
  },
  sidebarWrap: {
    width: isNarrow ? '100%' : 168,
    flexShrink: 0,
  },
  sidebarTitle: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  sidebar: {
    maxHeight: isNarrow ? 112 : undefined,
  },
  sidebarContent: {
    gap: 8,
    flexDirection: isNarrow ? 'row' : 'column',
    paddingVertical: isNarrow ? 4 : 0,
  },
  dayChip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    minWidth: isNarrow ? 72 : undefined,
    alignItems: 'center',
  },
  dayChipActive: { backgroundColor: THEME.primary, borderColor: 'rgba(255,255,255,0.25)' },
  dayChipText: { color: '#fff', fontWeight: '600', fontSize: 13 },
  panel: {
    flex: 1,
    minWidth: 0,
    width: isNarrow ? '100%' : undefined,
    padding: isNarrow ? 16 : 24,
    borderRadius: 14,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  panelTitle: { color: '#fff', fontSize: 22, fontWeight: '700', marginBottom: 16 },
  sectionTitle: { color: '#e2e8f0', fontSize: 16, fontWeight: '700', marginTop: 20, marginBottom: 8 },
  label: { color: '#cbd5e1', fontSize: 14, marginBottom: 8, marginTop: 12 },
  pathText: { color: '#94a3b8', fontSize: 12, marginBottom: 8 },
  imagePreview: {
    width: '100%',
    maxWidth: 320,
    aspectRatio: 1,
    borderRadius: 12,
    marginBottom: 8,
  },
  backgroundPreview: {
    width: '100%',
    maxWidth: 320,
    height: 180,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 8,
  },
  photoItem: {
    width: 120,
  },
  photoThumb: {
    width: 120,
    height: 120,
    borderRadius: 8,
  },
  photoPathText: { color: '#94a3b8', fontSize: 10, marginTop: 4 },
  photoActions: { flexDirection: 'row', gap: 4, marginTop: 6 },
  iconBtn: {
    backgroundColor: '#334155',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  iconBtnDisabled: { opacity: 0.35 },
  iconBtnDanger: {
    backgroundColor: '#7f1d1d',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  iconBtnText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8, marginTop: 4 },
  dangerBtn: {
    backgroundColor: '#7f1d1d',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    marginBottom: 8,
  },
  dangerBtnText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  input: {
    backgroundColor: '#1e293b',
    color: '#fff',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  textArea: { minHeight: 120, textAlignVertical: 'top' },
  giftMessageArea: { minHeight: 90, textAlignVertical: 'top' },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  primaryBtn: {
    backgroundColor: THEME.primary,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 16,
  },
  saveBtn: { backgroundColor: THEME.accent },
  saveBtnDisabled: { opacity: 0.55 },
  unsavedBanner: {
    backgroundColor: 'rgba(251, 191, 36, 0.95)',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  unsavedBannerText: {
    color: '#78350f',
    fontWeight: '700',
    fontSize: 13,
    textAlign: 'center',
  },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  secondaryBtn: {
    backgroundColor: '#334155',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  secondaryBtnText: { color: '#fff', fontSize: 13 },
  link: { color: '#93c5fd', marginTop: 16, textAlign: 'center' },
  linkInline: { color: '#93c5fd', fontSize: 13, fontWeight: '600' },
  });
